{% set name = "skpro" %}
{% set version = "2.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/skpro-{{ version }}.tar.gz
  sha256: 11e0202a7ddd6f1fba50e122ca24771df61f645e5b6120917f95bb07736821bc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.13
  run:
    - numpy <1.27,>=1.21.0
    - packaging
    - pandas <2.2.0,>=1.1.0
    - python >=3.6,<3.13
    - scikit-base <0.7.0,>=0.6.1
    - scikit-learn <1.4.0,>=0.24.0
    - scipy <2.0.0,>=1.2.0

test:
  requires:
    - pip
    - pytest
  imports:
    - skpro
    - skpro.base
    - skpro.benchmarking
    - skpro.datatypes
    - skpro.distributions
    - skpro.metrics
    - skpro.model_selection
    - skpro.registry
    - skpro.regression
    - skpro.utils

  commands:
    - pip check

about:
  home: https://pypi.org/project/skpro/
  summary: A unified framework for probability distributions and probabilistic supervised regression
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://skpro.readthedocs.io/en/latest/
  dev_url: https://github.com/sktime/skpro

extra:
  recipe-maintainers:
    - fkiraly
