{% set name = "skpro" %}
{% set version = "2.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/skpro-{{ version }}.tar.gz
  sha256: a5f03905a2ae75c403332d7ec8f08ff37314f76ffdad3cc902d062fcb9fa83d2

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy <2.2,>=1.21.0
    - packaging
    - pandas <2.3.0,>=1.1.0
    - python >={{ python_min }},<3.14
    - scikit-base <0.13.0,>=0.6.1
    - scikit-learn <1.6.0,>=0.24.0
    - scipy <2.0.0,>=1.2.0

test:
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  imports:
    - skpro
    - skpro.base
    - skpro.benchmarking
    - skpro.datatypes
    - skpro.distributions
    - skpro.metrics
    - skpro.model_selection
    - skpro.registry
    - skpro.regression
    - skpro.utils

  commands:
    - pip check

about:
  home: https://pypi.org/project/skpro/
  summary: A unified framework for probability distributions and probabilistic supervised regression
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://skpro.readthedocs.io/en/latest/
  dev_url: https://github.com/sktime/skpro

extra:
  recipe-maintainers:
    - yarnabrina
    - fkiraly
