github:
  branch_name: main
  tooling_branch_name: main
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_build:
  error_overlinking: true
  pkg_format: '2'
conda_forge_output_validation: true
test: native_and_emulated
